export const Trip = {
  drivername: "",
  permitendDate: "",
  transitType: "",
  permitstartDate: "",
  permitno: "",
  via: "",
  consigneeename: "",
  vehnum: "",
  material: "",
  qty: "",
  sms: "",
  imei: "",
  driverphone: "",
  vehtype: "",
  consignorname: "",
};
